//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HLE.rc
//
#define ID_BTN_RESTORE                  3
#define IDR_MAINFRAME                   98
#define IDR_HLTYPE                      99
#define IDR_HDTYPE                      100
#define IDS_OBJINFO_BUFFERLASER         100
#define IDR_EDITFRAME                   101
#define IDR_HETYPE                      102
#define IDD_ABOUTBOX                    103
#define IDS_OBJINFO_CCD                 103
#define IDC_EDIT_HANDLE_SIZE            104
#define IDS_OBJINFO_POSCALI             104
#define ID_INDICATOR_CALIBOX            105
#define ID_VIEW_PROPERTY                106
#define IDS_SELECTOBJECTFIRST           107
#define IDS_NEWDRAG_CMD                 108
#define IDC_UP                          108
#define IDS_ADDPOINT_CMD                109
#define IDC_DOWN                        109
#define IDS_DOTEDIT_CMD                 110
#define IDC_CHG                         110
#define IDS_DELDOT_CMD                  111
#define IDC_ADD                         111
#define IDS_MULTISELECT_CMD             112
#define IDC_SUB                         112
#define IDS_HITOTHEROBJ_CMD             113
#define ID_ZOOM_VIEW                    113
#define IDS_STOREDOC                    114
#define ID_ZOOM_WND                     114
#define IDS_DISPLAY                     115
#define IDS_OBJECTPROPERTY              116
#define IDS_MARKPARA                    117
#define IDS_CONVERTTOLINE               118
#define IDS_LOADLIB_ERROR               119
#define IDS_EXTFUNCTION_DESCRIBE        120
#define IDS_EXTFUNCTION_DESCRIBE_ENABLE 121
#define IDS_EXTFUNCTION_BMPMARK         122
#define IDS_EXTFUNCTION_MOTION          123
#define IDS_EXTFUNCTION_PRECISIONCALIBRATE 124
#define IDS_EXTFUNCTION_MULTICARD       125
#define IDS_EXTFUNCTION_ABLE_ENABLE     126
#define IDS_EXTFUNCTION_ABLE_DISABLE    127
#define IDS_START_HLEX                  128
#define IDS_STRING_CCD_NG_CONTINUE      129
#define ID_VIEW_CHANGE                  130
#define ID_VIEW_DRAW                    131
#define ID_VIEW_ZOOM                    132
#define IDC_CURSOR_ZOOMIN               132
#define IDD_SET_SCAN                    132
#define IDS_PROMPT_JUMP_OVERLAP         133
#define IDC_CURSOR_ZOOMOUT              134
#define IDS_EXTFUNCTION_DESCRIBE_NO     134
#define IDD_CHANGE                      135
#define IDS_CHANGECARD_FAIL             135
#define IDB_CHANGE_ROTATE               136
#define IDD_DRAW_CODEBAR                136
#define IDS_CHANGECARD_SUCC             136
#define IDS_BINDMUCHCARD                137
#define IDD_SET_TRACKER                 138
#define IDS_MODELSTEP                   138
#define IDS_MODELINCLINE                139
#define IDS_MODELCOLUMN                 140
#define IDR_DRAW                        140
#define IDS_MODELSPHERE                 141
#define IDR_ZOOM                        142
#define IDS_MODELTAPER                  142
#define IDD_MARK_NORMAL                 143
#define IDS_STEPPOSITION                143
#define IDS_STEPLONGTH                  144
#define IDC_CURSOR_CLICK                145
#define IDS_STEPWIDTH                   145
#define IDS_EXTFUNCTION_3DMARK          146
#define IDS_DSP_NOTSUPPORT3D            147
#define ID_INDICATOR_MARKTIME           148
#define ID_INDICATOR_MOTORLEFT          149
#define IDC_CURSOR_SHAPE                150
#define ID_INDICATOR_MOTORPOS           150
#define ID_INDICATOR_MOTORRIGHT         151
#define IDS_ERROR_TESTFILE              152
#define IDS_ERROR_FILECOUNT             153
#define IDD_SET_LASER                   154
#define IDS_MOTION_ROTATEAXIS           154
#define IDS_MOTION_LINEAXIS             155
#define IDS_LANGUAGE_CHANGE             156
#define IDS_ERROR_FILEFORMAT            157
#define IDD_CHANGE_POS                  158
#define IDS_MICROQR_CODETYPE_NUMBER     158
#define IDD_CHANGE_SCALE                159
#define IDS_MICROQR_CODETYPE_ALP        159
#define IDD_CHANGE_SIZE                 160
#define IDS_STRING_CCD_NG_EXIT          160
#define IDD_SET_CTRLCARD                161
#define IDS_MICROQR_CODETYPE_MIXCODE    161
#define IDB_CHANGE_POS                  162
#define IDS_BUILD_DRAG_MODULE           162
#define IDS_SET_LIMITBOX_FAIL           162
#define IDS_BUILD_ROTATE_MODULE         163
#define IDS_SET_MOTIONROTIO_FAIL        163
#define IDS_FIRST_RUN_WARNING           164
#define IDR_CHANGE                      165
#define IDS_INSTALLATION_FAULT          165
#define IDC_CURSOR_CROSS                166
#define IDS_LOGOUT_PROPT                166
#define IDD_SET_TOUCH                   168
#define IDD_SET_DAT468                  170
#define IDD_STYLE_SAVE                  171
#define IDD_CHANGE_ROTATE               172
#define IDB_CTRL_UpRt                   173
#define IDB_CTRL_LwLt                   174
#define IDB_CTRL_LwRt                   175
#define IDB_CTRL_LtRt1                  176
#define IDB_CTRL_UpLw                   177
#define IDI_ICON2                       178
#define IDI_ICON3                       179
#define IDI_ICON4                       180
#define IDI_ICON5                       181
#define IDI_ICON6                       182
#define IDD_SET_GRID                    183
#define IDD_SET_FOCUS                   184
#define IDB_CTRL_Pt                     185
#define IDB_CTRL_UpLt                   186
#define IDD_SET_CURVE                   189
#define IDD_DRAW_FILL                   199
#define IDD_DRAW_GRID                   201
#define IDD_DRAW_POLYGON                202
#define IDD_SERIAL_PAGE1                206
#define IDB_CTRL_CT                     206
#define IDB_ROTATE_CENTER               206
#define IDD_SERIAL_PAGE2                207
#define IDD_SERIAL_PAGE3                208
#define IDB_MULS4                       209
#define IDD_SERIAL_PAGE4                209
#define IDB_MULS1                       211
#define IDB_MULS3                       212
#define IDB_MULS2                       215
#define IDB_MULS5                       216
#define IDD_DIBold                      216
#define IDD_FORMVIEW_OTHER              218
#define IDC_CURSOR_MOVE                 219
#define IDC_CURSOR_CROSSIN              220
#define IDD_CODEBAR1                    224
#define IDB_CODEBAR1                    224
#define IDB_CODEBAR2                    225
#define IDD_CODEBAR3                    226
#define IDB_CODEBAR3                    226
#define IDD_CODEBAR2                    227
#define IDB_CODEBAR4                    227
#define IDD_CODEBAR4                    228
#define IDD_CODEBAR5                    229
#define IDD_MARK_PREVIEW                231
#define IDR_POP                         232
#define IDD_CODEBAR6                    233
#define IDR_MAINFRAME1                  233
#define IDD_SET_CENTER                  234
#define IDD_SET_FLY                     235
#define IDD_ERROR                       238
#define IDD_ARRAY                       239
#define IDD_ARRAYPOS                    240
#define IDD_TEXT_PAGE2                  242
#define IDD_TEXT_PAGE1                  243
#define IDD_TEXT_PAGE3                  245
#define IDD_SERIAL_SET                  246
#define IDD_TEXT_SERIAL                 246
#define IDD_SERIAL_PROCESS              251
#define IDD_SET_BOX10                   252
#define IDD_CALIBRATE_THEORY            252
#define IDD_CODEBAR7                    253
#define IDD_ALIGN                       254
#define IDB_ALIGN_TOP                   256
#define IDD_MARK_MULDOC                 256
#define IDB_ALIGN_MID                   257
#define IDD_SET_MULMARK                 257
#define IDD_SET_RUN                     257
#define IDB_ALIGN_BOTTOM                258
#define IDD_MARKDATA_STAT               258
#define IDB_ALIGN_LEFT                  259
#define IDD_CALIBRATE                   259
#define IDD_SET_CURRENT                 259
#define IDB_ALIGN_CEN                   260
#define IDD_CALIBRATE_RECT              260
#define IDB_ALIGN_RIGHT                 261
#define IDD_CALIBRATE_NET               261
#define IDD_CODEBAR_ADD                 262
#define IDD_CALIBRATE_GRADE             263
#define IDD_CODEBAR_FONT                263
#define IDD_CODEBAR_PROPER              264
#define IDI_ICON8                       265
#define IDD_DRAW_CODEBAR1               265
#define IDI_ICON_MARKSEL                265
#define IDD_PASSWORD_SETHARD            266
#define IDI_ICON_WARING1                268
#define IDD_PASSWORD_CHANGE             269
#define IDD_DATAMATRIX                  270
#define IDD_SET_DATAMATRIX2D            271
#define IDD_DIALOG1                     272
#define IDD_SET_PDF4172D                273
#define IDD_DRAW_DIB                    274
#define IDD_SET_TEXT                    275
#define IDD_CODEBAR_POSITIVE            276
#define IDD_SET_PASSWORD                278
#define IDD_SET_NEWPASSWORD             279
#define IDD_TEXT_SERIALSET              280
#define IDD_CODEBAR_OTHER               281
#define IDD_DLG_LOG                     283
#define IDD_SET_DAT3000                 284
#define IDD_SET_LAY                     285
#define IDD_SET_RIGHT                   286
#define IDD_SOCKET_DLG                  287
#define IDD_SET_FLYVIEW                 289
#define IDD_PLATTRF_DLG                 290
#define IDB_RED_NET                     290
#define IDB_GREEN_NET                   291
#define IDI_ICON9                       293
#define IDR_AVI1                        295
#define IDD_FLYSET_DLG                  298
#define IDD_SET_RECTANGLE               299
#define IDB_MOUSEROTATE_LT              300
#define IDB_MOUSEROTATE_TOP             301
#define IDB_MOUSEROTATE_RT              302
#define IDB_MOUSEROTATE_LEFT            303
#define IDB_MOUSEROTATE_RB              304
#define IDB_MOUSEROTATE_LB              305
#define ID_FILE_IMPORT                  306
#define ID_DRAW_HAND                    307
#define ID_DRAW_TEXT                    308
#define IDS_PANE_BUTTON                 309
#define IDS_PANE_PROGRESS               310
#define IDS_OBJHAVETXTORCODEBAR_COVERTTOLINE 311
#define IDS_MAX_MEASURE_LINE            312
#define IDS_DISMATCH_DOC                313
#define IDB_TITLE                       317
#define IDD_SET_QR2D                    318
#define IDD_SET_PCI3000                 321
#define IDD_FORMVIEW_INFO               322
#define IDD_TEXT_BASEDLG                325
#define IDD_TEXT_PAGE                   326
#define IDD_TEXT_BARCODEPAGE            327
#define IDD_TEXT_PAGE_TEXT              328
#define IDD_TEXT_PAGE_FNT               329
#define IDD_TEXT_PAGE_ROUND             330
#define IDD_BARCODE_DLG                 331
#define IDD_BAR_PAGE                    332
#define IDD_SET_BARTEXT                 333
#define IDI_ICON_A                      335
#define IDI_ICON_T                      336
#define IDI_ICON_P                      337
#define IDD_FILEREPLYRENAME             338
#define IDD_GRAYCOMPENSATE              339
#define IDD_REDLIGHT                    340
#define IDD_EXPORTPLT                   341
#define IDD_IMPORT                      342
#define IDD_HELPPATH                    343
#define IDD_SUPERCALI_MARK              344
#define IDB_BITMAP1                     345
#define IDC_CURSORDRAG                  347
#define IDD_ELLIPSET                    349
#define ID_POS                          350
#define ID_CHANG_DLG                    350
#define IDR_DISPLAY                     351
#define IDD_SELECT_POS                  354
#define IDI_ICON10                      355
#define IDI_ICON11                      356
#define IDI_ICON12                      357
#define IDI_ICON13                      358
#define IDI_ICON14                      359
#define IDI_ICON15                      360
#define IDI_ICON16                      361
#define IDI_ICON17                      362
#define IDI_ICON18                      363
#define IDD_DIALOG_PROPRETY             364
#define IDD_PARADLG                     365
#define IDI_UP                          366
#define IDI_DOWN                        367
#define IDD_MOVE_DLG                    368
#define IDD_SET_MARK_PARA_DLG           369
#define IDD_SPLASH                      369
#define IDI_ICON19                      371
#define IDI_ICON20                      372
#define IDD_DIALOG_OBJECT_LIST          373
#define IDD_DIALOG_STATUS_BAR           374
#define IDI_ICON_POLYLINE               379
#define IDI_ICON_RECTANGLE              380
#define IDI_ICON_LINE                   381
#define IDI_ICON_CIRCLE                 382
#define IDI_ICON_ELLIPSE                383
#define IDI_ICON_GRID                   384
#define IDI_ICON_POLYGON                385
#define IDI_ICON_TEXT                   386
#define IDI_ICON_CODEBAR                387
#define IDI_ICON_PLT                    388
#define IDI_ICON_BMP                    389
#define IDI_ICON_DXF                    390
#define IDI_ICON_MARKCP                 392
#define IDI_ICON22                      393
#define IDD_MAKECP_SET                  394
#define IDR_OBJCHANGE                   397
#define IDD_DIALOG_SETSORT              401
#define IDI_ICON_LOCK                   403
#define IDI_ICON_UNLOCK                 404
#define IDI_ICON_UNKNOW                 406
#define IDI_ICON_COMBINOBJ              407
#define IDI_SEL_RECT                    408
#define IDI_MOVE_MARK                   409
#define IDI_ICON_SCALE_HIGTH            410
#define IDI_ICON_SCALE_45_ANGLE         411
#define IDI_ICON_SCALE_WITH             412
#define IDI_ICON_ROTATE                 413
#define IDI_ICON_SCALE_135_ANGLE        414
#define IDR_ARRANGE                     416
#define IDC_CURSOR_MOVE_BOX             419
#define IDD_DIALOG_USER_LOGIN           420
#define IDD_DIALOG_USERRIGHTMNG         421
#define IDD_DIALOG_ADDUSER              422
#define IDD_DIALOG_USERRIGHTCFGMNG      423
#define IDD_DIALOG_EDITUSERRIGHTPASSWORD 424
#define IDD_DIALOG_EDITUSERNAME         425
#define IDD_DIALOG_CHANGUSER            426
#define IDD_DIALOG_INTENSITY            427
#define IDC_CURSOR_HAND                 428
#define IDR_DCP_AVI                     430
#define IDD_DIALOG_DCPMSG               431
#define IDI_ICON_DCPON                  434
#define IDI_ICON_DCPOFF                 435
#define IDD_DIALOG_SETLINEPOS           436
#define IDC_CURSOR_MLINE_V              437
#define IDC_CURSOR_MLINE_H              438
#define IDD_MARK_SPECIAL                439
#define IDD_SET_IO                      440
#define IDD_DIALOG_EDITFILL             441
#define IDD_DIALOG_OBJEDITFILL          443
#define IDD_DIALOG_FILLOBJMARKSET       444
#define IDD_DIALOG_EXTERNVIEW           450
#define IDR_SORTOBJ                     457
#define IDD_DIALOG_FPK                  459
#define IDD_DIALOG_FASTMARKSTOP         460
#define IDD_DIALOG_FPKSET               461
#define IDD_TEXTEDIT_DLG                463
#define IDC_CURSOR_OBJMOVE              465
#define IDD_DIALOG_BAREDIT              468
#define IDD_START_SPLASH                469
#define IDB_SPLASH                      474
#define IDC_CURSOR_VERDRAG              475
#define IDC_CURSOR_HVDRAG1              476
#define IDC_CURSOR_HORDRAG              477
#define IDC_CURSOR_HVDRAG2              482
#define IDI_ICON_DELAY                  484
#define IDI_ICON_INPUT                  485
#define IDI_ICON_OUTPUT                 486
#define IDD_SET_NODEDELAY               487
#define IDD_SET_NODEINPUT               488
#define IDD_SET_NODEOUTPUT              489
#define IDI_ICON_SPLINE                 490
#define IDI_ICON_ARC                    491
#define IDI_ICON_CIRCLE0                492
#define IDD_DIALOG_OBJ_PRECISIONSET     493
#define IDB_SHEARX                      494
#define IDI_ICON_FILLDIRE1              494
#define IDB_SHEARY                      495
#define IDI_ICON_FILLDIRE2              495
#define IDI_ICON_FILLREVE2              496
#define IDI_ICON_FILLREVE1              497
#define IDI_ICON_FILLLOOP               498
#define IDC_CURSOR_CODEBAR              499
#define IDI_ICON_LOOP                   499
#define IDD_DIALOG_PATHOPTIMIZE_SET     500
#define IDC_CURSOR_DOT                  500
#define IDC_CURSOR_ARC                  501
#define IDC_CURSOR_GRID                 502
#define IDC_CURSOR_POLY                 503
#define IDC_CURSOR_RECT                 504
#define IDC_CURSOR_TEXT                 505
#define IDB_BITMAP_SPLASH               506
#define IDD_DIALOG_OBJINFO_ARC          507
#define IDD_DIALOG_OBJINFO_CIRCLE       508
#define IDD_DIALOG_OBJINFO_SPLINE       509
#define IDI_ICON_MARK                   510
#define IDI_ICON_LASER                  511
#define IDI_ICON_LASERSTOP              512
#define IDI_ICON_NONE                   513
#define IDI_ICON_LASERSTOP2             514
#define IDI_ICON_DOT                    516
#define IDI_ICON_SCALE_LOCK             517
#define IDI_ICON_UNION                  518
#define IDD_DIALOG_ADDFILLSET           519
#define IDD_MARK_WHEEL                  520
#define IDD_DIALOG_MOTIONINFO_SET       521
#define IDD_DIALOG_ROTATEWHEEL_SET      522
#define IDD_DIALOG_OBJINFO_MOTORMOVE    523
#define IDD_DIALOG_OBJINFO_MOTORPOS     525
#define IDI_ICON_MOTORMOVE              527
#define IDD_DIALOG_PROWAIT              528
#define IDI_ICON_MOTORPOS               529
#define IDI_ICON_WHELLVIEW              532
#define IDI_ICON_CONDITIONS             537
#define IDI_ICON_CONDITIONE             538
#define IDD_DIALOG_RULER                539
#define IDD_DIALOG_RULEROBJ_SET         540
#define IDD_DIALOG_CHANGEOBJNAME        541
#define IDI_ICON_RULER_ALIGNTOP         542
#define IDI_ICON_RULER_ALIGNDOWN        543
#define IDD_DIALOG_CHANGECARD           545
#define IDD_DIALOG_EXTENDFUNCTION_INFO  547
#define IDD_DIALOG_3DLOAD               548
#define IDI_ICON_UP                     549
#define IDI_ICON_DOWN                   550
#define IDI_ICON_LEFT                   551
#define IDI_ICON_RIGHT                  552
#define IDD_DIALOG_TRANSFORM            553
#define IDB_BITMAP_3DROTE               554
#define IDC_CURSOR_VIEWROTE             555
#define IDD_DIALOG_MODIFYZ              556
#define IDI_ICON_GREEN                  557
#define IDI_ICON_RED                    558
#define IDD_BAR_PAGE_TEXT               559
#define IDR_MOTION                      561
#define IDD_DIALOG_TESTFOCUS            562
#define IDD_SET_LANGREGION              565
#define IDS_MICROQR_CODETYPE_BINARY     566
#define IDS_MICROQR_CODETYPE_KANJI      567
#define IDI_ICON_FALSE                  567
#define IDS_STRING568                   568
#define IDS_MICROQR_CODETYPE_CH         568
#define IDD_DIALOG_MOTORMOVE_WAIT       568
#define IDI_ICON1                       573
#define IDD_DIALOG_INTERSPACE           574
#define IDB_BITMAP_INTERSPACE           575
#define IDD_DIALOG_OBJINFO_BUFFER_LASER 576
#define IDI_ICON_BUFFER_LASER           577
#define IDD_SET_HANXINCODE              578
#define IDB_BITMAP_HANXIN               584
#define ID_CHANG_DLG_OTHER              585
#define IDI_ICON_ROTATE_X               586
#define IDI_ICON_ROTATE_Y               587
#define IDI_ICON_ROTATE_Z               588
#define IDD_DIALOG_OBJINFO_CCD          589
#define IDD_DIALOG_OBJ_POSCALI          590
#define IDI_ICON_CCD                    591
#define IDI_ICON_POSCALI                592
#define IDD_DIALOG_3DALIGN              593
#define IDD_DIALOG_LASERDOT             594
#define IDD_DIALOG_BROADEN              595
#define IDI_ICON_MOVEMARK               595
#define IDI_ICON_WHEELMARK              596
#define IDD_MARK_WHEEL2                 596
#define IDD_DIALOG_MOVEMARK_SET         597
#define IDD_DIALOG2                     598
#define IDD_DIALOG_NOTADMIN             598
#define IDC_COMBO_LANG                  1001
#define IDC_EDIT_END                    1002
#define IDC_RADIO_LINE_SOLID            1003
#define IDC_RADIO_LINE_DOTTED           1004
#define IDC_EDIT_DIRECTION              1005
#define IDC_EDIT_COLUMN_DISTANCE        1006
#define IDC_RADIO_RESIZE_INSIDE         1007
#define IDC_RADIO_RESIZE_OUTSIDE        1008
#define IDC_RADIO_LINE_NULL             1009
#define IDC_EDIT_FREQ                   1011
#define IDC_PROGRESS_MARK               1012
#define IDC_EDIT_TIMES                  1012
#define IDC_EDIT_PREFIX                 1012
#define IDC_EDIT_COLUMN                 1012
#define IDC_BUTTON_MARK                 1013
#define IDC_EDIT_POWER                  1013
#define IDC_EDIT_HEIGHT                 1013
#define IDC_BUTTON_STOP                 1014
#define IDC_CHECK17                     1014
#define IDC_CHECK2                      1015
#define IDC_CHECK3                      1016
#define IDC_CHECK4                      1017
#define IDC_CHECK5                      1018
#define IDC_BUTTON_APPLY                1019
#define IDC_CHECK6                      1019
#define IDC_CHECK7                      1020
#define IDC_CHECK8                      1021
#define IDC_CHECK9                      1022
#define IDC_RADIO_PATH_LINE             1023
#define IDC_CHECK10                     1023
#define IDC_CHECK11                     1024
#define IDC_CHECK12                     1025
#define IDC_TAB                         1026
#define IDC_CHECK13                     1026
#define IDC_STATIC3                     1027
#define IDC_CHECK14                     1027
#define IDC_CHECK15                     1028
#define IDC_EDIT_ANGLE                  1029
#define IDC_STATUS                      1029
#define IDC_CHECK16                     1029
#define IDC_COMBO_BARCODETYPE           1030
#define IDC_CHECK18                     1030
#define IDC_COMBO_ERR                   1030
#define IDC_COMBO_VERSION               1030
#define IDC_COMBO_ERROR                 1030
#define IDC_COMBO_EXCEPT                1030
#define IDC_RADIO_BASE_TL               1031
#define IDC_CHECK19                     1031
#define IDC_COMBO_MATRIXENN             1031
#define IDC_COMBO_BAUDRATE              1031
#define IDC_RADIO_BASE_TM               1032
#define IDC_CHECK20                     1032
#define IDC_RADIO_BASE_TR               1033
#define IDC_CHECK21                     1033
#define IDC_RADIO_BASE_ML               1034
#define IDC_LIST_DATA                   1034
#define IDC_LIST_DOC_OBJECT             1034
#define IDC_LIST_MARKINFO               1034
#define IDC_LIST_EDITDATA               1034
#define IDC_LIST_INFOLIST               1034
#define IDC_CHECK22                     1034
#define IDC_LIST_INFO                   1034
#define IDC_LIST_STEP                   1034
#define IDC_RADIO_BASE_MM               1035
#define IDC_CHECK23                     1035
#define IDC_RADIO_BASE_MR               1036
#define IDC_CHECK24                     1036
#define IDC_RADIO_BASE_BL               1037
#define IDC_CHECK25                     1037
#define IDC_RADIO_BASE_BM               1038
#define IDC_CHECK26                     1038
#define IDC_RADIO_BASE_BR               1039
#define IDC_CHECK27                     1039
#define IDC_CHECK28                     1040
#define IDC_CHECK29                     1041
#define IDC_CHECK30                     1042
#define IDC_CHECK31                     1043
#define IDC_CHECK32                     1044
#define IDC_CHECK34                     1045
#define IDC_CHECK35                     1046
#define IDC_CHECK36                     1047
#define IDC_CHECK37                     1048
#define IDC_CHECK38                     1049
#define IDC_CHECK39                     1050
#define IDC_CHECK40                     1051
#define IDC_CHECK41                     1052
#define IDC_CHECK42                     1053
#define IDC_CHECK43                     1054
#define IDC_CHECK44                     1055
#define IDC_CHECK45                     1056
#define IDC_CHECK46                     1057
#define IDC_CHECK47                     1058
#define IDC_CHECK48                     1059
#define IDC_CHECK49                     1060
#define IDC_CHECK50                     1061
#define IDC_CHECK51                     1062
#define IDC_CHECK52                     1063
#define IDC_CHECK53                     1064
#define IDC_CHECK54                     1065
#define IDC_CHECK55                     1066
#define IDC_CHECK56                     1067
#define IDC_CHECK57                     1068
#define IDC_CHECK58                     1069
#define IDC_EDIT_X                      1070
#define IDC_CHECK59                     1070
#define IDC_EDIT_Y                      1071
#define IDC_CHECK60                     1071
#define IDC_EDIT_R                      1072
#define IDC_CHECK61                     1072
#define IDC_EDIT_DIVX                   1072
#define IDC_CHECK62                     1073
#define IDC_EDIT_DIVY                   1073
#define IDC_CHECK63                     1074
#define IDC_EDIT_UNITPRECISION          1074
#define IDC_CHECK64                     1075
#define IDC_BUTTON_TEST                 1153
#define IDC_EDIT_F                      1154
#define IDC_EDIT_X1                     1159
#define IDC_EDIT_Y1                     1160
#define IDC_EDIT_SPACE                  1162
#define IDC_EDIT_Z                      1172
#define IDC_EDIT_I                      1173
#define IDC_BUTTON_DELETE               1186
#define IDC_EDIT_STYLE                  1187
#define IDC_EDIT_START                  1193
#define IDC_EDIT_RADIUS                 1196
#define IDC_EDIT_RADIUS2                1197
#define IDC_EDIT_LEN                    1199
#define IDC_EDIT_STEP                   1215
#define IDC_EDIT_INTERVAL               1216
#define IDC_EDIT_CURRENT                1217
#define IDC_EDIT_ROW                    1218
#define IDC_EDIT_COL                    1219
#define IDC_EDIT_NUM                    1220
#define IDC_BUTTON_SET                  1220
#define IDC_RADIO_POLYGON_LINE          1221
#define IDC_RADIO_POLYGON_STAR          1222
#define IDC_RADIO_POLYGON_CROSS         1223
#define IDC_EDIT_OPTION                 1232
#define IDC_SPIN_NUM                    1234
#define IDC_SLIDER_OPTION               1238
#define IDC_RADIO_CUSTOM                1239
#define IDC_RADIO_FROM                  1240
#define IDC_EDIT_ROW_DISTANCE           1242
#define IDC_LIST_PARA                   1248
#define IDC_CHECK_DEFAULT               1250
#define IDC_BUTTON_ADD                  1256
#define IDC_LIST_LAYER                  1256
#define IDC_BUTTON_SAVE                 1258
#define IDC_BUTTON_MOVE                 1259
#define IDC_COMBO_STYLE                 1260
#define IDC_BUTTON_ERASE                1262
#define IDC_STATIC_COUNT                1263
#define IDC_BUTTON_DEFAULT              1263
#define IDC_RADIO_STANDARD              1263
#define IDC_STATIC_SINGLE               1264
#define IDC_BUTTON_LASERDOT             1264
#define IDC_STATIC_TOTAL                1265
#define IDC_BUTTON_REFURBISH            1265
#define IDC_STATIC_IDLE                 1266
#define IDC_BUTTON_EDIT                 1266
#define IDC_STATIC_WORK                 1267
#define IDC_SLIDER_SPEED                1267
#define IDC_SLIDER0                     1267
#define IDC_EDIT_LEFT                   1268
#define IDC_BUTTON_START                1268
#define IDC_SLIDER1                     1268
#define IDC_EDIT_RIGHT                  1269
#define IDC_SLIDER2                     1269
#define IDC_CHECK_FILL                  1270
#define IDC_PROGRESS                    1270
#define IDC_SLIDER3                     1270
#define IDC_STATIC_VER                  1271
#define IDC_SLIDER4                     1271
#define IDC_STATIC_SPECIAL              1272
#define IDC_SLIDER5                     1272
#define IDC_BUTTON_DEL                  1276
#define IDC_EDIT_SHRINK                 1282
#define IDC_OPPOSITION_COL              1292
#define IDC_EDIT_CONTRAST               1298
#define IDC_BUTTON_LOAD                 1298
#define IDC_LIST                        1303
#define IDC_FILE_NAME                   1304
#define IDC_ADDON                       1306
#define IDC_EDIT_LINESPACE              1309
#define IDC_EDIT_FIXSPACE               1310
#define IDC_EDIT_INTERSPACE             1311
#define IDC_CHECK_CCW                   1312
#define IDC_EDIT_BROADENR               1312
#define IDC_EDIT_BROADEND               1313
#define IDC_EDIT_MATRIX_RADIUS          1314
#define IDC_EDIT_FILL_RADIUS            1315
#define IDC_RADIO_FONT_SHX              1320
#define IDC_RADIO_ALIGN_MID             1322
#define IDC_RADIO_PATH_ROUND            1323
#define IDC_RADIO_FONT_TTF              1327
#define IDC_COMBO_CHS                   1328
#define IDC_COMBO_EN                    1329
#define IDC_COMBO_NUM                   1330
#define IDC_COMBO_USER                  1331
#define IDC_EDIT_FIX                    1339
#define IDC_CHECK_LINE_CONNECT          1339
#define IDC_BUTTON_SERIAL               1343
#define IDC_BUTTON_TTF                  1344
#define IDC_EDIT_WIDTHFACTOR            1345
#define IDC_EDIT_CHARSPACE              1346
#define IDC_RADIO_ALIGN_LEFT            1347
#define IDC_RADIO_ALIGN_RIGHT           1348
#define IDC_CHECK_INSIDE                1350
#define IDC_COMBO_SERIAL                1358
#define IDC_STATIC_START                1363
#define IDC_STATIC_END                  1364
#define IDC_STATIC_DATE                 1365
#define IDC_LIST_DOCNAME                1383
#define IDC_BUTTON_UP                   1384
#define IDC_BUTTON_DOWN                 1385
#define IDC_EDIT_MOVE                   1387
#define IDC_EDIT_DELAY                  1389
#define IDC_PROGRESS_DWONLOAD           1392
#define IDC_RADIO2                      1394
#define IDC_RADIO7                      1395
#define IDC_CHECK_UPDATE                1396
#define IDC_CHECK_CEN                   1397
#define IDC_BUTTON_GETIO                1398
#define IDC_BUT_ADD                     1398
#define IDC_BUT_BARCODESET              1398
#define IDC_BUTTON_GRAYCURRENT          1398
#define IDC_BUTT_SELPOS                 1398
#define IDC_BUT_DEL                     1403
#define IDC_DEL                         1403
#define IDC_CENTER                      1403
#define IDC_BUTTON_LAYER1               1403
#define IDC_BUTTON_VIEW                 1403
#define IDC_BUTTON_EXIT                 1403
#define IDC_MAKECOPY                    1404
#define IDC_BUTTON_LAYER2               1404
#define IDC_BUTTON_VIEW2                1404
#define IDC_BUTTON_LAYER3               1405
#define IDC_MAKE_OTHER                  1405
#define IDC_BUTTON_LAYER4               1406
#define IDC_CHECK_MANUAL                1407
#define IDC_BUTTON_LAYER5               1407
#define IDC_BUTTON_LAYER6               1408
#define IDC_BUTTON_LAYER7               1409
#define IDC_CHECK_AUTO                  1410
#define IDC_STATIC_MARKNUM              1413
#define IDC_STATIC_MARKTIME             1414
#define IDC_BTN_APPLY                   1414
#define IDC_BUTTON_MODSTEP              1414
#define IDC_CHECK_LASER                 1433
#define IDC_CHECK_KEEP                  1447
#define IDC_EDIT_INIVAL                 1449
#define IDC_EDIT_PASSWORD               1461
#define IDC_NUM                         1462
#define IDC_SINGLE_TIME                 1463
#define IDC_TOTAL_TIME                  1464
#define IDC_STATIC_NUM                  1475
#define IDC_STATIC1                     1476
#define IDC_COMBO                       1477
#define IDC_RADIO1                      1492
#define IDC_RADIO_LASER                 1492
#define IDC_RADIO_GRAY                  1493
#define IDC_RADIO4                      1493
#define IDC_RADIO10                     1494
#define IDC_EDIT_LINENUM                1495
#define IDC_CHECK1                      1499
#define IDC_CHECK_CUSTOM                1499
#define IDC_CHECK_FIXSPACE              1499
#define IDC_CHECK_REV                   1499
#define IDC_CHECK33                     1500
#define IDC_CHECK_HOLLOW                1500
#define IDC_EDIT1                       1502
#define IDC_EDIT_FORMAT                 1502
#define IDC_EDIT_BINTEXT                1502
#define IDC_EDIT_WIDTH                  1502
#define IDC_EDIT_DOTTIME                1502
#define IDC_EDIT_Dest0                  1502
#define IDC_RULER                       1502
#define IDC_POSX                        1502
#define IDC_MOVEX                       1502
#define IDC_EDIT_NEWSORT                1502
#define IDC_EDIT_ADDUSERNAME            1502
#define IDC_EDIT_LINE_POS               1502
#define IDC_EDIT_IO                     1502
#define IDC_EDIT_MARKCOUNT              1502
#define IDC_EDIT_INTERVALTIME           1502
#define IDC_EDIT_ROTATE                 1502
#define IDC_EDIT_PRECISION              1502
#define IDC_EDIT_STARTX                 1502
#define IDC_EDIT_COUNT                  1502
#define IDC_EDIT_Pitch                  1502
#define IDC_EDIT_DIAMETER               1502
#define IDC_EDIT_VALUE_ROTATE           1502
#define IDC_EDIT_LINE_VALUE0            1502
#define IDC_EDIT_DIA                    1502
#define IDC_EDIT_JUMPCOUNT              1502
#define IDC_EDIT_NAME                   1502
#define IDC_EDIT_CARDNAME               1502
#define IDC_EDIT_3DFILE                 1502
#define IDC_EDIT_TESTDIST               1502
#define IDC_EDIT_TOBASEZ                1502
#define IDC_EDIT_Dest1                  1503
#define IDC_POSY                        1503
#define IDC_MOVEY                       1503
#define IDC_EDIT_PASSWORD1              1503
#define IDC_EDIT_NEWUSERNAME            1503
#define IDC_EDIT_STARTY                 1503
#define IDC_EDIT_AddDis                 1503
#define IDC_EDIT_PPR                    1503
#define IDC_EDIT_DIVANGLE               1503
#define IDC_EDIT_LINE_VALUE1            1503
#define IDC_EDIT_QRLS                   1503
#define IDC_EDIT_HOLLOW_WIDTH           1503
#define IDC_EDIT_MARKSPEED              1503
#define IDC_RADIO_FIX                   1504
#define IDC_EDIT_DISTANCE               1504
#define IDC_EDIT_QFre                   1504
#define IDC_EDIT_Dest2                  1504
#define IDC_SIZEX                       1504
#define IDC_MOVE_STEP_VALUE             1504
#define IDC_EDIT_PASSWORD2              1504
#define IDC_EDIT_CENTERX                1504
#define IDC_EDIT_AddAngle               1504
#define IDC_EDIT_LINE_VALUE2            1504
#define IDC_EDIT_FILLNO                 1504
#define IDC_EDIT_NUMBERCOUNT            1504
#define IDC_EDIT_OUT_DELAY              1504
#define IDC_EDIT_DIAMETER2              1504
#define IDC_EDIT_LoopCompate            1505
#define IDC_EDIT_Dest3                  1505
#define IDC_SIZEY                       1505
#define IDC_EDIT_OLDPASSWORD            1505
#define IDC_EDIT_CENTERY                1505
#define IDC_EDIT_LINE_VALUE3            1505
#define IDC_EDIT_JUMP_DELAY             1505
#define IDC_DATE                        1506
#define IDC_EDIT_ACCTime                1506
#define IDC_EDIT_Dest4                  1506
#define IDC_ROTATE                      1506
#define IDC_EDIT_ENDX                   1506
#define IDC_EDIT_MODEL                  1506
#define IDC_EDIT_Dest5                  1507
#define IDC_PROPEX                      1507
#define IDC_EDIT_QFREQ                  1507
#define IDC_CHECK_MODIFY                1507
#define IDC_EDIT_ENDY                   1507
#define IDC_INFO                        1508
#define IDC_SPACE                       1508
#define IDC_SPACE_X                     1508
#define IDC_EDIT_Soure0                 1508
#define IDC_PROPEY                      1508
#define IDC_EDIT_ARCR                   1508
#define IDC_EDIT_Soure1                 1509
#define IDC_SHEARX                      1509
#define IDC_DELAY_MIN                   1509
#define IDC_SPACE_Y                     1510
#define IDC_EDIT_Soure2                 1510
#define IDC_SHEARY                      1510
#define IDC_EDIT_STARTANGLE             1510
#define IDC_EDIT_Soure3                 1511
#define IDC_EDIT_ENDANGLE               1511
#define IDC_POSZ                        1511
#define IDC_DELAY_MAX                   1511
#define IDC_EDIT_Soure4                 1512
#define IDC_EDIT_Soure5                 1513
#define IDC_RADIO_DA                    1518
#define IDC_CHECK_ALIGN                 1526
#define IDC_CHECK_SCALE                 1535
#define IDC_CHECK_MARK                  1537
#define IDC_CHECK_VER                   1539
#define IDC_CHECK_SEL_MARK              1541
#define IDC_CHECK_SAVE                  1541
#define IDC_RADIO3                      1543
#define IDC_EDIT_LAYER                  1543
#define IDC_RADIO_FRAME                 1543
#define IDC_RADIO_WORKTYPE              1543
#define IDC_EDIT_FILL                   1544
#define IDC_RADIO5                      1544
#define IDC_RADIO6                      1545
#define IDC_EDIT_FILLSCAL               1545
#define IDC_RADIO8                      1546
#define IDC_RADIO9                      1547
#define IDC_CHECK_Center                1549
#define IDC_CHECK_PLT_BETTER            1550
#define IDC_SERIAL                      1569
#define IDC_RADIO_NORMAL                1589
#define IDC_RADIO_R                     1590
#define IDC_RADIO_A                     1591
#define IDC_VALUE                       1592
#define IDC_CURSOR_MOUSEROTATE          1593
#define IDC_CURSOR_TB_DRAG              1594
#define IDC_CURSOR_LR_DRAG              1595
#define IDC_CURSOR_SPLINE               1596
#define IDC_CURSOR_ELLIPSE              1597
#define IDC_STATIC_MARK                 1598
#define IDC_COMBO_ERRORLEVEL            1604
#define IDC_COMBO_SIZE                  1605
#define IDC_TAB_BASE                    1620
#define IDC_STATIC_IO                   1620
#define IDC_BUT_MODIFY                  1621
#define IDC_TAB_TEXT                    1622
#define IDC_CHECK_DEBUG                 1622
#define IDC_RADIO_SERIAL                1623
#define IDC_RADIO_SIGNALTYPE            1623
#define IDC_RADIO_TIME                  1624
#define IDC_STATIC_DOC                  1624
#define IDC_DATE_EDIT                   1626
#define IDC_SERIAL_EDIT                 1627
#define IDC_FIX_EDIT                    1628
#define IDC_CHECK_REMOVEORG             1632
#define IDC_RADIO_RED                   1634
#define IDC_EDIT_LowGray                1634
#define IDC_TIME_INFO                   1635
#define IDC_EDIT_UpGray                 1635
#define IDC_COORD                       1636
#define IDC_EDIT_NARROW                 1637
#define IDC_RADIO_ROW                   1645
#define IDC_RADIO_COL                   1646
#define IDC_RADIO_TYPELINE              1647
#define IDC_RADIO_TYPES                 1648
#define IDC_CHECK_LOOP                  1649
#define IDC_RADIO_DIFF                  1657
#define IDC_EDIT_LOOPNUM                1657
#define IDC_File_Prompt                 1658
#define IDC_EDIT_LOOPDIST               1658
#define IDC_RADIO_DOTMATRIX             1658
#define IDC_PIC_GrayResult              1659
#define IDC_PIC_GraySource              1660
#define IDC_TAB_MARKPARA                1662
#define IDC_TAB_OBJEDIT                 1662
#define IDC_STATIC_WARNING              1666
#define IDC_STATIC_RED                  1667
#define IDC_CHECK_UnExportFill          1670
#define IDC_CHECK_Scale100              1671
#define IDC_BTN_ADJUSTPAGE              1672
#define IDC_BUTTON_DELSTEP              1672
#define IDC_MAKECOPY_SET                1678
#define IDC_EDIT_SCAN_COUNT             1680
#define IDC_COMBO_PRECIS_K              1681
#define IDC_CHECK_FILL_COLOR            1682
#define IDC_EDIT_LINE_SPACE             1682
#define IDC_BUTTON_MOVE_UP              1683
#define IDC_BUTTON_MOVE_DWON            1684
#define IDC_BUTTON_MOVE_LEFT            1685
#define IDC_BUTTON_EXTENDOBJ            1685
#define IDC_BUTTON_MOVE_RIGTH           1686
#define IDC_BTN_EXPORT                  1690
#define IDC_BTN_DELETE                  1691
#define IDC_CHECK_LAYMARKPARA           1696
#define IDC_CHECK_MARKNORMAL            1697
#define IDC_CHECK_MARKMULDOC            1698
#define IDC_CHECK_CREATEOBJ             1699
#define IDS_PROMPT_SCALE_MINIMUM        1700
#define IDC_CHECK_OBJEDIT               1700
#define IDS_PROMPT_OPENGRAYSCALE_FAIL   1701
#define IDC_CHECK_SYSTEMSET             1701
#define IDS_PROMPT_SAVEGRAYSCALE_FAIL   1702
#define IDC_CHECK_CALIBSET              1702
#define IDS_PROMPT_CANNOTFIND           1703
#define IDC_CHECK_FILESAVE              1703
#define IDS_PROMPT_CREATEINPORTFOLDER_FAIL 1704
#define IDC_CHECK_OPENFILE              1704
#define IDS_PROMPT_INPORTFILE1          1705
#define IDC_CHECK_ADV_PARA              1705
#define IDS_PROMPT_INPORTFILE2          1706
#define IDC_CHECK_MNG                   1706
#define IDS_PROMPT_INPORTFILE3          1707
#define IDC_LIST_USERNAMELIST           1707
#define IDS_NODEFAULTUSER               1708
#define IDC_EDIT_NEWPASSWORD1           1709
#define IDS_NOUSERINFO                  1709
#define IDC_EDIT_NEWPASSWORD2           1710
#define IDS_USERINFOISNOOK              1710
#define IDC_EDIT_OLDUSERNAME            1711
#define IDC_CHECK_SET_DEFAULTUSER       1713
#define IDC_BUTTON_IMPORT               1714
#define IDC_BUTTON_EXPORT               1715
#define IDC_STATIC_DISPMSG              1715
#define IDC_EDIT_BRIGHTNESS             1717
#define IDC_CHECK_GO_BACK               1717
#define IDC_RADIO_CHANG_POS             1718
#define IDC_CHECK_AUTOFILL              1718
#define IDC_RADIO_EXCHANG_POS           1719
#define IDC_STATIC_ORD_MSG              1720
#define IDC_EDIT_SINGLELINE_MARKCOUNT   1722
#define IDC_CHECK_LASERSTATUS           1723
#define IDC_EDIT_NARROW_LINENUM         1723
#define IDC_CHECK_RED                   1724
#define IDC_EDIT_DOTRADIUS              1724
#define IDC_STATIC_DCPMSGDISP           1725
#define IDC_CHECK_ISKILL_OLDOBJ         1726
#define IDC_BUTTON_ERRORSTATUS          1728
#define IDC_CHECK_CENTERPOS             1729
#define IDC_STATIC_OBJPOS               1730
#define IDC_BUTTON_GET                  1731
#define IDC_BUTTON_APPLYFILL            1732
#define IDC_COMBO_MARKPARA              1734
#define IDC_CHECK_ISMARKFILL            1736
#define IDC_COMBO_MARKLAYERCOUNT        1737
#define IDC_CHECK_ISMARKFRAM            1738
#define IDC_CHECK_LOOPMARK              1740
#define IDC_COMBO_MARKPARALIST          1742
#define IDC_CHECK_ISFIRSTMARKFILL       1743
#define IDC_CHECK_SELMARK               1744
#define IDC_CHECK_USEED                 1745
#define IDC_STATIC_PANEL                1746
#define IDC_CHECK_ISRESMARK             1746
#define IDC_STATIC_NOTE                 1748
#define IDC_CHECK_OPT                   1749
#define IDC_STATIC_LINESPACE            1750
#define IDC_STATIC_GROUP                1751
#define IDC_BUTTON_TEXTDEL              1763
#define IDC_BUTTON_SELMARK              1763
#define IDC_BUTTON_TEXTEDIT             1764
#define IDC_BUTTON_FASTMARK             1764
#define IDC_BUTTON_TEXTADD              1765
#define IDC_BUTTON_ADVANCE              1766
#define IDC_STATIC_OBJVIEW              1769
#define IDC_BUTTON_ROTATE               1772
#define IDC_BUTTON_IMPORTTEMPLATE       1778
#define IDC_BUTTON_EXPORTTEMPLATE       1779
#define IDC_RADIO_TEMPLATE              1780
#define IDC_EDIT_LX                     1781
#define IDC_EDIT_LY                     1782
#define IDC_EDIT_RX                     1783
#define IDC_EDIT_RY                     1784
#define IDC_BUTTON_OFFSET               1785
#define IDC_CHECK_LOOPMULMARK           1793
#define IDC_STATIC_MARKINFO             1794
#define IDC_BUTTON_DOWN_OUTLINEDATA     1795
#define IDC_STATIC_SOFTID               1796
#define IDC_STATIC_LIMITCODE            1797
#define IDC_STATIC_TYPECODE             1798
#define IDC_STATIC_DOG_VERSION          1799
#define IDC_STATIC_DOG_TIME             1800
#define IDC_EDIT_TEXTID                 1801
#define IDC_STATIC_RECTH                1803
#define IDC_STATIC_RECTW                1804
#define IDC_RADIO_FONT_USER             1805
#define IDC_STATIC_CHS                  1807
#define IDC_STATIC_EN                   1808
#define IDC_STATIC_USER                 1809
#define IDC_CHECK_PREVIEW               1817
#define IDC_STATIC_PREVIEWZOOM          1818
#define IDC_EDIT_MODEL_NU               1819
#define IDC_STATIC_RECT1                1820
#define IDC_CHECK_ENABLE                1820
#define IDC_STATIC_RECT2                1821
#define IDC_RADIO_FILL1                 1821
#define IDC_COMBO_TextType              1822
#define IDC_RADIO_FILL2                 1822
#define IDC_STATIC_FontType             1823
#define IDC_BUTTON_STYLE                1823
#define IDC_COMBO_FontType              1824
#define IDC_STATIC_TextType             1825
#define IDC_CHECK_KEEPANGLE             1825
#define IDC_STATIC_RECT4                1826
#define IDC_CHECK_EQUADIST              1826
#define IDC_STATIC_RECT3                1827
#define IDC_EDIT_BEAMCOMP               1827
#define IDC_STATIC_FontHeight           1828
#define IDC_EDIT_STARTOFFSET            1828
#define IDC_STATIC_FontTTF              1829
#define IDC_EDIT_ENDOFFSET              1829
#define IDC_COMBO_FontTTF               1830
#define IDC_EDIT_LINEREDU               1830
#define IDC_EDIT_MINJUMP                1831
#define IDC_EDIT_CurNu                  1831
#define IDC_CHECK_REMOVEFILL            1833
#define IDC_SPIN1                       1833
#define IDC_EDIT_CurX                   1834
#define IDC_EDIT_LINEREDU_END           1834
#define IDC_EDIT_CurY                   1835
#define IDC_STATIC_WARN                 1835
#define IDC_CHECK_FILLFIRST             1836
#define IDC_RADIO_FONT_MATRIX           1837
#define IDC_STATIC_PRECIS_K             1838
#define IDC_STATIC_WINDOW               1839
#define IDC_STATIC_1                    1840
#define IDC_STATIC_SHX                  1841
#define IDC_STATIC_TTF                  1842
#define IDC_STATIC_CUSTOM               1843
#define IDC_STATIC_MATRIX               1844
#define IDC_COMBO_MATRIXCHS             1845
#define IDC_STATIC_CHSM                 1846
#define IDC_STATIC_ENNM                 1847
#define IDC_CHECK_MATRIX                1848
#define IDC_EDIT_HEIGHREV               1849
#define IDC_BUTTON_ADDFILLSET           1850
#define IDC_EDIT_HOLLOW_HEIGHT          1850
#define IDC_RADIO_PROCESS               1852
#define IDC_COMBO_AxisType              1853
#define IDC_EDIT_LineEmptySpeed         1855
#define IDC_EDIT_LineWorkSpeed          1856
#define IDC_EDIT_HomeHighSpeed          1857
#define IDC_EDIT_HomeLowSpeed           1858
#define IDC_EDIT_REmptySpeed            1859
#define IDC_EDIT_RWorkSpeed             1860
#define IDC_EDIT_EmptyTAcc              1861
#define IDC_EDIT_WorkTAcc               1862
#define IDC_EDIT_HomeTAcc               1863
#define IDC_COMBO_AxisNo                1864
#define IDC_RADIO_MotorDire             1865
#define IDC_EDIT_VALUE_LINE             1866
#define IDC_RADIO_MOVEMODEL             1867
#define IDC_EDIT_ROTATE_VALUE0          1868
#define IDC_EDIT_ROTATE_VALUE1          1869
#define IDC_CHECK_HOME                  1869
#define IDC_EDIT_ROTATE_VALUE2          1870
#define IDC_STATIC_ROTATEMARKINFO       1870
#define IDC_EDIT_ROTATE_VALUE3          1871
#define IDC_STATIC_PROINFO              1877
#define IDC_CHECK_SAVECONTOUR           1877
#define IDC_EDIT_MOVEVALUE              1878
#define IDC_RADIO_MOVETYPE              1880
#define IDC_LIST_GRAYLIST               1881
#define IDC_RADIO_TYPE                  1882
#define IDC_EDIT_DISTANCE_CIRCLE        1883
#define IDC_EDIT_DISTANCE_LINE          1884
#define IDC_EDIT_LINECOUNT              1886
#define IDC_EDIT_ADD                    1887
#define IDC_LIST_OBJ                    1893
#define IDC_CHECK_REMOVELASTLINE        1894
#define IDC_CHECK_VIEW                  1896
#define IDC_STATIC_VIEW                 1897
#define IDC_RADIO_ALIGNDOWN             1898
#define IDC_RADIO_ALIGNTOP              1899
#define IDC_BUTTON_ALIGN                1900
#define IDC_BUTTON_SETSOFT0             1901
#define IDC_BUTTON_CLOSE                1901
#define IDC_CHECK_AUTOSOFT0             1902
#define IDC_BUTTON_MOTORHOME            1903
#define IDC_CHECK_ENABLED               1905
#define IDC_CHECK_HARDORG               1906
#define IDC_COMBO_CARDINFO              1908
#define IDC_EDIT_CARDID                 1911
#define IDC_EDIT_3DOFFSETX              1911
#define IDC_EDIT_STEPWIDTH              1911
#define IDC_EDIT_SETFOCUS               1911
#define IDC_BUTTON_RENAME               1912
#define IDC_BUTTON_3DFILESEL            1912
#define IDC_BUTTON_SETTOBASEZ           1912
#define IDC_BUTTON_DEFLNG               1912
#define IDC_RADI_3DSHAPE                1913
#define IDC_COMBO_3DBASE                1914
#define IDC_EDIT_3DOFFSETY              1915
#define IDC_EDIT_LONG                   1915
#define IDC_EDIT_3DROTATEZ              1916
#define IDC_EDIT_STARTR                 1916
#define IDC_EDIT_3DOFFSETZ              1917
#define IDC_EDIT_X0                     1918
#define IDC_EDIT_Y0                     1919
#define IDC_EDIT_Z0                     1922
#define IDC_EDIT_Z1                     1923
#define IDC_STATIC_PARA                 1924
#define IDC_STATIC_INCLINE              1925
#define IDC_STATIC_P0                   1926
#define IDC_STATIC_P0X                  1927
#define IDC_STATIC_P0Y                  1928
#define IDC_STATIC_P0Z                  1929
#define IDC_STATIC_P1                   1930
#define IDC_STATIC_P1X                  1931
#define IDC_STATIC_P1Y                  1932
#define IDC_STATIC_P1Z                  1933
#define IDC_STATIC_TAPER                1934
#define IDC_STATIC_RADIUS               1935
#define IDC_STATIC_LONG                 1936
#define IDC_CHECK_MARKINSIDE            1937
#define IDC_STATIC_COLUMN               1938
#define IDC_STATIC_RADIUS2              1939
#define IDC_STATIC_STEP                 1940
#define IDC_BUTTON_ADDSTEP              1941
#define IDC_STATIC_STEPWIDTH            1942
#define IDC_RADIO_ILDRIRECT             1943
#define IDC_CHECK_NEWOBJECT             1944
#define IDC_STATIC_STARTR               1945
#define IDC_STATIC_ENDR                 1946
#define IDC_EDIT_ENDR                   1947
#define IDC_CHECK_VERTICAL              1948
#define IDC_STATIC_TIPCOLUMN            1949
#define IDC_STATIC_TIPTAPER             1950
#define IDC_CHECK_PARITY                1951
#define IDC_COMBO_CODETYPE              1952
#define IDC_RADIO_TransType             1953
#define IDC_COMBO_SYMBOL                1954
#define IDC_COMBO_SHAPE                 1955
#define IDC_CHECK_WELD                  1956
#define IDC_CHECK_InterFilter           1957
#define IDC_CHECK_BROADEN               1958
#define IDC_RADIO02                     1959
#define IDC_COMBO_ERROR_LEVEL           1960
#define IDC_RADIO_CALITYPE              1962
#define IDC_CHECK_SET_POS               1963
#define IDC_CHECK_PRINTINVERSE          1964
#define IDC_RADI_FILLTYPE               1965
#define IDC_EDIT_FILL_DIS               1966
#define IDC_RADIO_AI_TYPE               1967
#define IDC_SLIDER_FREQ                 1969
#define IDC_RADIO_SPEED                 1970
#define IDC_RADIO_FREQ                  1971
#define IDC_RADIO_DISTANCE              1972
#define IDC_COMBO_CODEPAGE              1973
#define IDC_CHECK_LANG                  1974
#define IDC_STATIC_MATRIX_RADIUS        1976
#define IDC_CHECK_WHEELMARK             1976
#define IDC_STATIC_MATRIX_FILLR         1977
#define IDC_EDIT_ENCODEPPR              1978
#define IDC_STATIC_TIP                  1978
#define ID_INDICATOR_USER               29141
#define ID_INDICATOR_POS                29142
#define ID_INDICATOR_LENGTH             29143
#define IDS_USERISINLIST                29144
#define IDS_USERORPASSWORDNOOK          29145
#define IDS_NOMNGRIGHT                  29146
#define IDS_PASSWORDCANNTNULL           29147
#define IDS_PASSWORDISNOOK              29148
#define IDS_USERNAMECANNTNULL           29149
#define IDS_USERNAMEISNOEXIST           29150
#define IDS_OLDPASSWORDNOOK             29151
#define IDS_OBJLIST                     29153
#define IDS_SPECIALLIST                 29154
#define IDS_MARKTYPESET                 29155
#define IDS_MARKFILLEDIT                29156
#define IDS_DBSPECIAL                   29157
#define IDS_SORTOBJ                     29158
#define IDS_YH_ADD                      31460
#define IDS_YH_NOSEL                    31461
#define IDS_YH_CHANGE                   31462
#define IDS_YH_DELETE                   31463
#define IDS_YH_PROMPT                   31464
#define IDS_YH_DEFAULT                  31465
#define IDS_YH_NAME                     31466
#define IDS_YH_DULNAME                  31467
#define IDS_TITLE_FILEIMPORT            31468
#define IDS_FILE_FORMAT                 31469
#define IDS_NOOBJECT                    31470
#define IDS_MARK_ON                     31479
#define IDS_MARK_PAUSE                  31480
#define IDS_ERROR_TIMER                 31482
#define IDP_OLE_INIT_FAILED             31484
#define IDS_TITLE_DRAW                  31485
#define IDS_TITLE_CHANGE                31487
#define IDS_TITLE_MAINFRAME             31488
#define IDS_PROMPT_ZOOMIN               31489
#define IDS_PROMPT_ZOOMOUT              31490
#define IDS_TITLE_ZOOM                  31491
#define IDS_PROMPT_ELLIPSE              31492
#define IDS_PROMPT_RECT                 31493
#define IDS_PROMPT_LINE                 31494
#define IDS_PROMPT_CURVE                31495
#define IDS_PROMPT_MOVE                 31496
#define IDS_PROMPT_SCALE                31497
#define IDS_PROMPT_SCALE_X              31498
#define IDS_PROMPT_SCALE_Y              31499
#define IDS_PROMPT_REDO                 31500
#define IDS_PROMPT_UNDO                 31501
#define IDS_COMMAND_MOVE                31502
#define IDS_COMMAND_ADDNODE             31503
#define IDS_COMMAND_SCALE               31504
#define IDS_COMMAND_DRAG                31505
#define IDS_COMMAND_CLICK               31506
#define IDS_COMMAND_DELETE              31507
#define IDS_COMMAND_ROTATE              31508
#define IDS_COMMAND_SELECT              31509
#define IDS_COMMAND_COPY                31510
#define IDS_COMMAND_GROUP               31511
#define IDS_COMMAND_UNGROUP             31512
#define IDS_COMMAND_PASTE               31513
#define IDS_COMMAND_SHEAR               31514
#define IDS_PROMPT_GRID                 31515
#define IDS_COMMAND_FILL                31517
#define IDS_PROMPT_POLYGON              31519
#define IDS_TITLE_SERIAL                31520
#define IDS_TITLE_PROPERTY              31521
#define IDS_TITLE_LAYER                 31522
#define IDS_LAYER_NOSELECT              31523
#define IDS_LAYER_OTHER                 31524
#define IDS_ERROR_DOCUMENT              31525
#define IDS_LAYER_DEL                   31526
#define IDS_LAYER_MOVE                  31527
#define IDS_COMMAND_SETLAY              31528
#define IDS_TITLE_CODEBAR               31529
#define IDS_COMMAND_DRAWSET             31530
#define IDS_ARRAY_LOAD                  31551
#define IDS_ARRAY_SAVE                  31552
#define IDS_COMMAND_ARRAY               31553
#define IDS_TITLE_TEXT_TEXT             31554
#define IDS_TITLE_TEXT_FONT             31555
#define IDS_TITLE_TEXT_STYLE            31556
#define IDS_MULDOC_NOPATH               31586
#define IDS_MULDOC_SAVE                 31587
#define IDS_MULDOC_LOAD                 31588
#define IDS_MARKSTAT_DATEFORMAT         31592
#define IDS_MARKSTAT_TIMEFORMAT         31593
#define IDS_ERROR_PASSWORD_SETHARD      31599
#define IDS_ERROR_CAPTION               31600
#define IDS_ERROR_PASSWORD_NOEQU        31601
#define IDS_ERROR_PASSWORDOLD           31602
#define IDS_ERROT_OUTAREA               31616
#define IDS_ERROR_FILENAME              31617
#define IDS_ERROR_PASSWORD              31618
#define IDS_ERROR_NEWPW                 31619
#define IDS_ERROR_OTHER                 31620
#define IDS_ONLY_ONE_COPY               31649
#define IDS_DRAWBAR_SELLIST             31650
#define IDS_ERROR_OPENFILE              31652
#define IDS_LAYER_COLOR                 31658
#define IDS_RIGHT_NO                    31660
#define IDS_FONT_FILE_ERR               31697
#define IDS_HZK_OPENERROR               31698
#define IDS_LAYER_LIMIT                 31709
#define IDS_BARTITLE                    31718
#define IDS_TEXTTITLE                   31719
#define IDS_FNTTITLE                    31720
#define IDS_ROUNDTITLE                  31721
#define IDS_MANAGER                     31724
#define IDS_USER                        31725
#define IDS_PLT_EXPORT_ERR              31726
#define IDS_BINDSET_FILE                31727
#define ID_MARK_NORMAL                  32779
#define ID_SET_CTRLCARD                 32782
#define ID_MARK_PREVIEW                 32783
#define IDS_INPUTNEWNUM                 32784
#define IDS_INPUTOTHERNUM               32785
#define ID_CALIBRATE                    32788
#define ID_EDIT_DELETE                  32791
#define IDS_SELOBJ                      32793
#define IDS_COPY_DB_PROP                32794
#define IDS_CREATSUCCSED                32795
#define IDS_SELSORTMSG                  32796
#define ID_ZOOM_OUT                     32804
#define ID_ZOOM_IN                      32805
#define ID_ZOOM_ALL                     32807
#define ID_ZOOM_SELECT                  32808
#define ID_ZOOM_PAGE                    32809
#define ID_DRAW_RECTANGLE               32813
#define ID_DRAW_ELLIPSE                 32814
#define ID_DRAW_POLYGON                 32815
#define ID_DRAW_GRID                    32816
#define ID_DRAW_FILL                    32820
#define ID_DRAW_CLICK                   32821
#define ID_GROUP                        32828
#define ID_UN_GROUP                     32829
#define ID_OPTION                       32832
#define ID_SET_BOX                      32839
#define ID_SET_HARDWARE                 32841
#define IDM_TouchSignal                 32842
#define ID_CHANGE_POS                   32844
#define ID_CHANGE_ROTATE                32845
#define ID_CHANGE_SCALE                 32846
#define ID_CHANGE_SIZE                  32847
#define ID_CHANGE_CENTER                32901
#define ID_CHANGE_MIRROR_X              32907
#define ID_CHANGE_MIRROR_Y              32908
#define ID_CHANGE_CCW                   32913
#define ID_CHANGE_CW                    32914
#define ID_SET_TRACKER                  32916
#define ID_VIEW_LAYER                   32917
#define ID_DRAW_CODEBAR                 32919
#define IDS_TEMPLATEARRAY_LOAD          32920
#define IDS_TEMPLATEARRAY_SAVE          32921
#define ID_DRAW_SET                     32936
#define ID_SET_CENTER                   32938
#define ID_SET_FLY                      32939
#define ID_ARRAY                        32940
#define ID_SET_BOX10                    32943
#define IDS_NOFINDFONT                  32944
#define ID_SNAP                         32949
#define ID_ALIGN                        32950
#define ID_MARK_MUL                     32951
#define ID_FILE_MULDOC                  32953
#define ID_DRAW_BMP                     32954
#define ID_MARKDATA_STAT                32956
#define ID_MARK_STAT                    32957
#define IDS_NAME                        32957
#define ID_CALIBRATE_NET                32958
#define IDS_TYPE                        32958
#define IDS_NUM                         32959
#define ID_ZOOM_RECT                    32964
#define IDS_UNKNOW                      32965
#define IDS_LINES                       32966
#define IDS_RECT                        32967
#define IDS_TEXT                        32968
#define IDS_JUMPSTRING                  32969
#define IDS_ELLIPSE                     32970
#define IDS_GRID                        32971
#define IDS_POLYGON                     32972
#define IDS_CODEBAR                     32973
#define IDS_GROUP                       32974
#define ID_SET_LAYER                    32975
#define IDS_BMP                         32975
#define IDS_DELAY                       32976
#define IDS_INPUT                       32977
#define IDS_OUTPUT                      32978
#define ID_SINGLE_EMB                   32979
#define ID_MULTI_EBM                    32980
#define ID_PARA_EMBSET                  32981
#define IDS_CONDITIONS                  32982
#define IDS_CONDITIONE                  32983
#define ID_BUTTON32995                  32995
#define ID_DRAW_MATRIXBAR               32997
#define ID_DRAW_BARTEXT                 32998
#define IDM_GRAYCURRENT                 33001
#define IDM_GRAYCOMPENSATE              33002
#define IDM_EXPORT_PLT                  33003
#define IDM_HELPPATH                    33004
#define ID_ZOOMOPER                     33005
#define ID_ZOOMOFF                      33006
#define ID_DRAW_DRAG                    33007
#define ID_DISPLAY                      33008
#define ID_HIDE                         33009
#define IDD_MOVEACCU                    33010
#define IDD_CONVERT                     33011
#define ID_MOD_LAYER_COLOR              33012
#define ID_OBJLIST_DEL                  33013
#define ID_DELDOT                       33014
#define ID_JOINDOT                      33015
#define ID_MOVEACCU                     33016
#define ID_MENUITEM33017                33017
#define ID_SPLITDOT                     33018
#define ID_SEL_ALLSTROKE                33020
#define ID_LOCK_LAYER                   33021
#define ID_UNLOCK_LAYER                 33022
#define ID_SET_CURPOINT_BEGIN           33023
#define ID_FILTER_POINT                 33024
#define ID_REVERRIS_STROKE              33025
#define ID_FILTER_CURDOC_POINT          33027
#define ID_KILL_ANGLE                   33028
#define ID_SORTOBJ                      33029
#define ID_AUTOSORTOBJ                  33030
#define ID_BUTTON_GO_SORT               33039
#define IDD_ADDONETREE                  33040
#define ID_LOAD_OBJLIST                 33041
#define ID_UNLOAD_OBJLIST               33042
#define ID_EQUAL_WIDTH                  33044
#define ID_EQUAL_HEIGHT                 33045
#define ID_EQUAL_WH                     33046
#define ID_ALIGN_LEFT                   33047
#define ID_ALIGN_RIGHT                  33048
#define ID_ALIGN_TOP                    33049
#define ID_ALIGN_BOTTOM                 33050
#define ID_DISTANCE_X                   33051
#define ID_DISTANCE_Y                   33052
#define IDM_KEYBIND_SET                 33053
#define IDM_RIGHTMNG                    33054
#define ID_ADDUSER                      33055
#define ID_DELUSER                      33056
#define ID_EDITUSERNAME                 33057
#define ID_EDITUSERPASSWORD             33058
#define IDM_CHANGEUSER                  33059
#define ID_MARK_SPC                     33061
#define ID_RED_PREVIEW                  33062
#define ID_FAST_MARK                    33063
#define ID_EDIT_DB_COPY                 33064
#define ID_EDIT_DB_PASTE                33065
#define ID_SELSORT                      33068
#define ID_ALIGN_X                      33069
#define ID_ALIGN_Y                      33070
#define ID_DWONLOAD                     33071
#define ID_DWONLOAD_MARKDATA            33072
#define ID_CLEAR_DOWNLOAD               33073
#define ID_SET_TESTIO                   33074
#define ID_JOINTSTROKE_CURDOC           33076
#define ID_SET_CALIBRATE                33077
#define ID_SET_LASERPARA                33078
#define ID_PATH_OPTIMIZE                33079
#define ID_PATH_NORMAL                  33080
#define ID_AJUST_M                      33081
#define ID_ADJUST_M                     33082
#define ID_SELECT_LAYER                 33083
#define ID_UNSELECT_LAYER               33084
#define ID_SET_USERFONT                 33085
#define ID_DOWN_MUL                     33086
#define ID_SORT_QUICK                   33087
#define ID_MOVE_PREV                    33088
#define ID_MOVE_NEXT                    33089
#define ID_MOVETO_FIRST                 33090
#define ID_MOVETO_LAST                  33091
#define ID_DRAW_TIMER                   33092
#define ID_DRAW_INPUT                   33093
#define ID_DRAW_OUTPUT                  33094
#define ID_DRAW_SPLINE                  33097
#define ID_SPLINE_EDIT                  33102
#define ID_DRAW_ARC_3PT                 33113
#define ID_DRAW_ARC_CENTER              33115
#define ID_DRAW_CIRCLE                  33117
#define ID_ARC_EDIT                     33119
#define ID_CIRCLE_EDIT                  33121
#define ID_PRECISION_SET                33122
#define ID_DRAW_DOT                     33129
#define ID_LOGOUT_USER                  33130
#define ID_UNION                        33131
#define ID_UNUNION                      33132
#define ID_EDIT_WHEEL                   33136
#define ID_MARK_WHEEL                   33137
#define ID_DRAW_MOTORMOVE               33138
#define ID_DRAW_SETPOS                  33139
#define ID_BMP_Intensity                33140
#define ID_DRAW_CONDITION               33141
#define ID_EDIT_RULER                   33142
#define ID_OBJ_CHANGENAME               33143
#define ID_CHANGE_CARD                  33145
#define ID_EXTFUNCTION_INFO             33147
#define ID_MODULE_SWITCH                33148
#define ID_MODULE_LOAD                  33149
#define ID_MODULE_TRANSFORM             33150
#define ID_MODIFYZ                      33151
#define ID_FILE_IMPORT_VECTOR           33154
#define ID_FILE_IMPORT_BMP              33155
#define ID_FILE_IMPORT_NC               33156
#define ID_3DVIEW_XY                    33157
#define ID_3DVIEW_YZ                    33158
#define ID_3DVIEW_XZ                    33159
#define ID_3DVIEW_XYZ                   33160
#define ID_CHECK_FOCUS                  33162
#define ID_ROTATEWHEEL_SET              33163
#define ID_MOTIONINFO_SET               33165
#define ID_EYE_DISPLAY                  33168
#define ID_LANG_CHANGE                  33170
#define ID_LANG_CHINESE                 33173
#define ID_LANG_ENGLISH                 33175
#define ID_LANG_CHINESES                33176
#define ID_LANG_CHINESET                33177
#define IDD_EDIT_WELD                   33178
#define ID_RUNHLEX                      33179
#define IDD_EDIT_InterFilter            33182
#define ID_ASSISTANT_POINT              33184
#define ID_33187                        33187
#define ID_DRAW_BUFFERLASER             33189
#define IDM_HELP_CHS                    33193
#define IDM_HELP_ENGLISH                33194
#define ID_DRAW_CCD                     33198
#define ID_DRAW_POSCALI                 33200
#define ID_MODULE_ALIGN                 33202
#define IDD_EDIT_BROADEN                33205
#define ID_MARK_WHEEL2                  33211
#define ID_MOTION_MARK_PARAM            33214
#define ID_VIEW_OBJECTLISTDIALOG        33215
#define ID_VIEW_PROPERTYDIALOG          33216
#define IDS_LAYER                       57347
#define IDS_DOT                         59415
#define IDS_NO_SEL_EDITPOINT            61449
#define IDS_SELRANGE_HAVEDUMP           61450
#define IDS_SELONEDOT_ONLY              61451
#define IDS_THELINEISNOTCIRCL           61452
#define IDS_THETWOPOINTTOOSMALL         61453
#define IDS_FILTERPOINT_CMD             61454
#define IDS_EXTENDOBJ_CMD               61455
#define IDS_APPLYALLOBJECT              61456
#define IDS_STRISEXITSORTPRO            61458
#define IDS_IFSETSTARTDOT               61459
#define IDS_GSORT_NO_LINE               61460
#define IDS_COMMAND_COMTOTREE           61461
#define IDS_SELGROUPBYNUM_CMD           61462
#define IDS_MALIGN                      61463
#define IDS_AOTUSORTLESSSIXOBJ          61464
#define IDS_BASE_PARA                   61465
#define IDS_ADV_PARA                    61466
#define IDS_MARKSET_NUM                 61472
#define IDS_MARKSET_LAYER               61473
#define IDS_MARKSET_FRAM                61474
#define IDS_MARKSET_FILL                61475
#define IDS_MARKSET_FILLFIRST           61476
#define IDS_OFFLINESTATUS_ISREDOWN      61477
#define IDS_OFFLINETOONLINE             61478
#define IDS_START                       61479
#define IDS_STOP                        61480
#define IDS_ISCLEARDOWNLOAD             61481
#define IDS_SPEED                       61482
#define IDS_Q_FREQ                      61483
#define IDS_Q_RLS                       61484
#define IDS_START_CALIBRATEDLG          61485
#define IDS_START_LASERPARA             61486
#define IDS_JOINSTROKE                  61487
#define IDS_POS_ABSOLUTE                61488
#define IDS_POS_RELATIVE                61489
#define IDS_PATHOPTIMIZE_NOTE           61490
#define IDS_NORMALPATH_NOTE             61491
#define IDS_START_ADJUSTM               61492
#define IDS_DOWNNORMALOK                61493
#define IDS_DAMAGEFILE                  61494
#define IDS_TEXT_TYPE_FIX               61495
#define IDS_TEXT_TYPE_SERIAL            61496
#define IDS_TEXT_TYPE_TIME              61497
#define IDS_FONT_TYPE_TTF               61498
#define IDS_FONT_TYPE_SHX               61499
#define IDS_FONT_TYPE_USER              61500
#define IDS_SPLINE                      61501
#define IDS_STRING_ISCLOSE              61502
#define IDS_ARC                         61503
#define IDS_CIRCLE                      61504
#define IDS_INVALIDINPUT                61505
#define IDS_ERRORRANGE                  61506
#define IDS_OBJINFO_ARC                 61507
#define IDS_OBJINFO_CIRCLE              61508
#define IDS_COMMAND_PATHOPTIMIZE        61509
#define IDS_MARK_STOP                   61510
#define IDS_FONT_TYPE_MATRIX            61511
#define IDS_UNION                       61512
#define IDS_MOTORMOVE                   61513
#define IDS_MOTORPOS                    61514
#define IDS_OPENCALIFILE_ERROR          61515
#define IDS_MAKE_WHEELSTROKE            61516
#define IDS_COMMAND_AUTOSEGMENT         61517
#define IDS_ERROR_SEGMENT               61518
#define IDS_ERROR_OBJPRO                61519
#define IDS_USER_USER                   61520
#define IDS_USER_TYPE                   61521
#define IDS_INTENSITY_GRAY              61522
#define IDS_INTENSITY_COUNT             61523
#define IDS_RULER_EDITWARNING           61524
#define IDS_RULER_OBJECT                61525
#define IDS_RULER_JUMPCOUNT             61526
#define IDS_RULER_VISIBLEMARK           61527
#define IDS_RULER_DECIMALDIGITS         61528
#define IDS_RULER_PRIORITY              61529
#define IDS_COMMAND_UNION               61530
#define IDS_COMMAND_UNUNION             61531
#define IDS_COMMAND_CHANGE_LAYER        61532

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        599
#define _APS_NEXT_COMMAND_VALUE         33217
#define _APS_NEXT_CONTROL_VALUE         1979
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
